### ISSUE TITLE
Collectibles (pets, boss drops etc)

### ISSUE THREAD

**Issue by Azunyan-** [daanheskes/OSRS-Idle-Clicker#7]
I'd say basically anything that is dropped from a boss should be possible to get.

You might need to add bosses. A crude bank system where you can store items like planks or something could be cool, people hoard stuff in OSRS already.

Looking good so far btw!
Keep it up

**Comment by daanheskes** [comment]
Currently I'm not planning to have a bank system added, as I think other features are more important as of now. But bosses are definitely on the list. Those will drop the "Drop only" items.

**Comment by daanheskes** [comment]
Boss drops have been added, more will be added later.
